abstract_phrase_base = [
    "Resonating reveries of amnesia",
    "Murmurs from the boundless abyss",
    "Shattered musings within the depths",
    "Endless seclusion, an enigmatic coexistence",
    "Shifting spirits interwoven",
    "Fleeting reverberations in the celestial waltz",
    "Veiled yearnings in the twilight's embrace",
    "Hushed cries amidst the cacophony",
    "Play of the hidden psyche",
    "The journey of genuine love knows no tranquil path",
    "O, cosmic jesters these earthly souls become!",
    "Affection gazes beyond sight, into the boundless intellect",
    "In her diminutive form, she radiates intensity",
    "The madman, the adorer, and the visionary",
    "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife",
    "I won't go out with you and my thong!",
    "That was a Bridget Jones diary moment",
    "I'm an excellent worker If you could see my filofax, you would see, and if you could see my flat, you would see",
    "Bridget Jones, wanton sex goddess, with a very bad man between her thighs... Mother x",
    "Hi, I'm Bridget Jones Actually my name's Bridget Jones Hi!",
    "Every breath you take, every move you make, every bond you break, every step you take, I'll be watching you",
    "Message in a bottle, send an S.O.S. to the world",
    "Don't stand so close to me",
    "Fields of gold, you'll remember me when the west wind moves upon the fields of barley",
    "If I ever lose my faith in you, there'd be nothing left for me to do",
    "Wrapped around your finger, I'll be wrapped around your finger",
    "Shape of my heart, if I told you that I loved you, would you maybe think I'm lyin'?",
]
